title: "Assingment 1"
subtitle: "Some technical stuff"
course: "AI NFT Buzzwording 101"
authors:
  -marvin:
    name: "Marvin"
    id: "1234"
date-label: "Date:"
author-labels:
  name: "Author"
  id: "ID"
institution: "MIT"
department: "Computer Science"
logo:
  path: "mtu"
  display: true
